apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-prf5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-prf5
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-prf5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-prf5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-prf5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gycw-tenant/rhtap-demo-app/hacbs-test-project-prf5@sha256:f9bef26b3ac1ec97d0303068a1135458c70df796bdff6cb13d1dd8881d5371a4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
