apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-prf5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gycw-tenant/rhtap-demo-app/hacbs-test-project-prf5@sha256:62a1bed4a6155af411d902a3cba584751674fd4e0ae5b06d278e7cbade2edba1
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
